 export const DISHES_LOADING='DISHES_LOADING';
 export const ADD_DISHES= 'ADD_DISHES';
 export const DISHES_FAILED = 'DISHES_FAILED';
 export const ADD_COMMENTS= 'ADD_COMMENTS';
 export const COMMENTS_FAILED = 'COMMENTS_FAILED';

 export const PROMS_LOADING='PROMS_LOADING';
 export const ADD_PROMS= 'ADD_PROMS';
 export const PROMS_FAILED = 'PROMS_FAILED';

 export const LEADERS_LOADING='LEADERS_LOADING';
 export const ADD_LEADERS= 'ADD_LEADERS';
 export const LEADERS_FAILED = 'LEADERS_FAILED';

